Allow including view_id in output to disambiguate multiple GA properties
MeltanoLabs/tap-google-analytics pull request #92
Opened 2023-01-19 16:31 UTC by menzenski

See some more discussion here: https://github.com/meltano/meltano/issues/7165#issuecomment-1397105636

I am trying to set things up to use tap-google-analytics to load 49 GA properties into Redshift. As things stand today there's no information in the records from this tap that associates it with a specific GA property. This PR is an attempt to provide the ability to disambiguate them.

I'm not sure this is the best way, so feedback is very welcome!

2023-01-19 18:16 UTC, edgarrmondragon commented
@pnadolny13 I'm curious wdyt of this?

2023-01-19 19:06 UTC, pnadolny13 commented
@menzenski @edgarrmondragon I cant think of any reason why we shouldnt support this, especially since its backwards compatible.

I think this PR is missing logic to add the new field to the schema though, see https://github.com/MeltanoLabs/tap-google-analytics/blob/3348b2d1e4c36cb4a69e4aeefe042c828bfc8f80/tap_google_analytics/client.py#L393. If I had to guess this would work but the view attribute would get skipped because its not selected in the schema. Does that make sense?

2023-01-19 20:25 UTC, menzenski commented
@pnadolny13 updated!

2023-01-19 20:44 UTC, edgarrmondragon approved these changes

2023-01-23 14:51 UTC, pnadolny13 requested changes
@menzenski when I ran the tests for this I got a failure, see my other related comment. Would you also mind running `poetry run black tap_google_analytics/`? It had one formatting fix to suggest.

2023-01-23 14:51 UTC, pnadolny13 commented on tap_google_analytics/client.py
> +        if self.include_view_id_in_output:
```suggestion
        if self.config.get("include_view_id_in_output", False):
```

@menzenski I like your way of defining this in the init a shared but it looks like the super() in the init uses this before `include_view_id_in_output` is set so it cant find `include_view_id_in_output`. I'm open to other alternatives but heres a suggestion that worked for me.

2023-06-06 21:58 UTC, closed without merging